### ISSUE TITLE
Bugged Casual end scoreboard/Engineer level issue

### ISSUE THREAD

**Issue by ThatCatt-0-o** [yesod404/yesodCollyHUD#16]
Hey ive already mentioned it on the site tf2huds.dev but theres a bug on the end of a casual match everybody's statistics, username and class are all packed up in the same spot and this happens most of the time, its very rare for me to see it being normal again.
Theres also another bug i wanted to point out where as the engineer a number is in front of your building's progress to the next level so its like 2150/200 the building's level is fine thought. 
![Capture d'écran 2024-07-30 181533](https://github.com/user-attachments/assets/8494f743-9434-4bf2-bd6f-4fe9e721820e)

**Comment by yesod404** [comment]
I am still trying to figure out what causes the casual match problem, unfortunately. However, a simple fix is once you get this bug do hud_reloadscheme, and the problem will never happen until you restart TF2.

The engineer bug occurs because of the Medigun Icons, in the most recent patches, I added the ability to swap it out, in the folder Medigun Name, the version that gives the entire team will fix the problem with Engineer.

**Comment by ThatCatt-0-o** [comment]
Alright thank you very much ! I'll see next time i play if the command fixes this issue wich im pretty sure it will and i'll check for the engie issue. Anyways your HUD is great, ive been using it for the past 3 or so weeks and its just perfect for me, good job and keep up man ! Thanks for the reply and have a good day !

**Comment by yesod404** [comment]
I forget to update you, but one of the recent patches made it so that if you use the medigun icons, the engineer levels will no longer bug out. Instead of being something like 2150/200, it will be 2/150/200

**Comment by yesod404** [comment]
ITS FIXED AND CASUAL HAS ALL THE STUFF
