### ISSUE TITLE
scoreboard bug when using r_drawviewmodels 0

### ISSUE THREAD

**Issue by r3dnasa** [yesod404/yesodCollyHUD#5]
![20240614025209_1](https://github.com/yesod404/yesodCollyHUD/assets/82971054/0fa45d3b-f124-4f8f-8864-f80182daa5bf)
disabling viewmodels while viewing the scoreboard makes the screen completely opaque, also netgraph font seems to be way too small

**Comment by r3dnasa** [comment]
as an update: seems to only happen when theres something with glow on the screen

**Comment by yesod404** [comment]
So this comes from in this hud. When you press the tab, you'll notice stuff will get blurry, and many things will hide because it is scripted to give an FPS boost when you pull it up, so it probably removes glowing stuff. However, with 64-bit TF2, there would not be a reason to try and give this desperate performance boost, so I will remove it. Thank you for bringing this up.

**Comment by r3dnasa** [comment]
okay thank you, cl_showpos and cl_showfps text also seem to be small too
